version: "3.9"

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.6.24
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - openwebui_data:/app/backend/data
    networks: [ragnet]

  nginx:
    image: nginx:latest
    container_name: nb5-nginx
    depends_on:
      - open-webui
    ports:
      - "3100:8080"  # access at http://localhost:3000
    volumes:
      - ./nb5-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks: [ragnet]
    # 🐧 Linux only: uncomment so host.docker.internal resolves to host gateway
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
  postgres:
    image: ankane/pgvector:latest
    container_name: nb5-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpass
    ports:
      - "5432:5432"              # exposes to your FastAPI on host
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./pg-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raguser -d ragdb"]
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  ragnet:
    driver: bridge

volumes:
  openwebui_data:
  pg_data:
